Update iosfa.yml

diff --git a/.github/workflows/iosfa.yml b/.github/workflows/iosfa.yml
--- a/.github/workflows/iosfa.yml
+++ b/.github/workflows/iosfa.yml
@@ -1,59 +1,81 @@
-START=21000
-END=22000
+name: IOSFA Range Export
 
-OUTPUT="resultado.txt"
-> "$OUTPUT"
+on:
+  workflow_dispatch:
 
-for USER_ID in $(seq $START $END); do
+jobs:
+  validar:
+    runs-on: ubuntu-latest
+    permissions:
+      contents: write
 
-  echo "Procesando USER $USER_ID"
+    steps:
+      - name: Ejecutar scraping
+        shell: bash
+        run: |
+          START=21000
+          END=22000
 
-  URL="http://validador.iosfa.gob.ar:5080/Afiliados/Titular/Editar/${USER_ID}"
+          OUTPUT="resultado.txt"
+          > "$OUTPUT"
 
-  RESPONSE=$(curl -s -L "$URL" \
-    -H "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8" \
-    -H "Accept-Language: es-419,es;q=0.9" \
-    -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/145.0.0.0 Safari/537.36" \
-    -H "Cookie: _gid=GA1.3.2022856683.1771469080; _ga_56029ZBE95=GS2.1.s1771555226$o2$g0$t1771556191$j60$l0$h0; IOSFABackOffice=4368BAD61229F777A3023C951E4620667C6B200FA8E8B28E41124A4D06D59C73AD8FE86E76EB21A44E77FEE334D71C582094EC148D579B56BD76E883CEFA2ABF9D0C30A3FC12C46E3F2B41EF5CB5F2000D361A67851002F1FCB5C1059B3FC59DEB944F04; ASP.NET_SessionId=x4weqd2ynqjb1r4tpyp0tpiu; _ga=GA1.1.1393734416.1771468464; _ga_XHVVC4C0Q1=GS2.1.s1771570487$o4$g1$t1771572785$j49$l0$h0") || true
+          for USER_ID in $(seq $START $END); do
 
-  if [[ -z "$RESPONSE" ]]; then
-    echo "USER $USER_ID = ERROR HTTP" >> "$OUTPUT"
-    continue
-  fi
+            echo "Procesando USER $USER_ID"
 
-  if [[ "$RESPONSE" != *"FUERZA DE ORIGEN:"* ]]; then
-    echo "USER $USER_ID = SIN DATOS" >> "$OUTPUT"
-    continue
-  fi
+            URL="http://validador.iosfa.gob.ar:5080/Afiliados/Titular/Editar/${USER_ID}"
 
-  extract() {
-    VALUE=$(echo "$RESPONSE" | grep -oP "$1" 2>/dev/null | head -n1)
-    VALUE=$(echo "$VALUE" | sed 's/^[ \t]*//;s/[ \t]*$//')
-    echo "${VALUE:-}"
-  }
+            RESPONSE=$(curl -s -L "$URL" \
+              -H "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8" \
+              -H "Accept-Language: es-419,es;q=0.9" \
+              -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/145.0.0.0 Safari/537.36" \
+              -H "Cookie: _gid=GA1.3.2022856683.1771469080; _ga_56029ZBE95=GS2.1.s1771555226$o2$g0$t1771556191$j60$l0$h0; IOSFABackOffice=4368BAD61229F777A3023C951E4620667C6B200FA8E8B28E41124A4D06D59C73AD8FE86E76EB21A44E77FEE334D71C582094EC148D579B56BD76E883CEFA2ABF9D0C30A3FC12C46E3F2B41EF5CB5F2000D361A67851002F1FCB5C1059B3FC59DEB944F04; ASP.NET_SessionId=x4weqd2ynqjb1r4tpyp0tpiu; _ga=GA1.1.1393734416.1771468464; _ga_XHVVC4C0Q1=GS2.1.s1771570487$o4$g1$t1771572785$j49$l0$h0") || true
 
-  TIPO=$(extract '(?<=dxgv dx-al\" style=\"border-left-width:0px;border-right-width:0px;\">).*?(?=</td>)')
-  ESTADO=$(extract '(?<=color:#CC0000;font-weight:bold;border-left-width:0px;border-right-width:0px;\">).*?(?=</td>)')
-  APELLIDO=$(extract '(?<=txtApellidos\" value=\").*?(?=\")')
-  NOMBRE=$(extract '(?<=txtNombres\" value=\").*?(?=\")')
-  CODIGO=$(extract '(?<=txtCodigoCredencial&#39;\)\" value=\").*?(?=\")')
-  DNI=$(extract '(?<=txtRefExterna\" value=\").*?(?=\")')
-  ESTADO_CIVIL=$(extract '(?<=cboEstadoCivil_I\" type=\"text\" value=\").*?(?=\")')
-  EDAD=$(extract '(?<=txtEdad\" value=\").*?(?=\")')
-  FECHA_NAC=$(extract '(?<=txtFecNacimiento_I\" type=\"text\" value=\").*?(?=\")')
-  DISCAPACIDAD=$(extract '(?<=cboDiscapacitado_I\" type=\"text\" value=\").*?(?=\")')
-  FUERZA=$(extract '(?<=afiFA\">).*?(?=</span>)')
-  VIGENCIA=$(extract '(?<=txtFecha_Vigencia_I\" type=\"text\" value=\").*?(?=\")')
-  ALTA_ADMIN=$(extract '(?<=txtFecha_Alta_Administrativa_AcAs.*?value=\").*?(?=\")')
-  PROVINCIA=$(extract '(?<=cboProvincia_I\" type=\"text\" value=\").*?(?=\")')
-  LOCALIDAD=$(extract '(?<=cboLocalidad_I\" type=\"text\" value=\").*?(?=\")')
-  CALLE=$(extract '(?<=txtCalle\" value=\").*?(?=\")')
-  NUMERO=$(extract '(?<=txtNumero&#39;\).*?value=\").*?(?=\")')
+            if [[ -z "$RESPONSE" ]]; then
+              echo "USER $USER_ID = ERROR HTTP" >> "$OUTPUT"
+              continue
+            fi
 
-  LINE="TIPO = $TIPO | ESTADO = $ESTADO | APELLIDO = $APELLIDO | NOMBRE = $NOMBRE | CODIGO = $CODIGO | DNI = $DNI | ESTADO CIVIL = $ESTADO_CIVIL | EDAD = $EDAD | FECHA DE NACIMIENTO = $FECHA_NAC | DISCAPACIDAD = $DISCAPACIDAD | FUERZAS DE ORIGEN = $FUERZA | VIGENCIA = $VIGENCIA | ALTA ADMINISTRATIVA = $ALTA_ADMIN | PROVIDENCIA = $PROVINCIA | LOCALIDAD = $LOCALIDAD | CALLE = $CALLE | NUMERO = $NUMERO"
+            if [[ "$RESPONSE" != *"FUERZA DE ORIGEN:"* ]]; then
+              echo "USER $USER_ID = SIN DATOS" >> "$OUTPUT"
+              continue
+            fi
 
-  echo "$LINE" >> "$OUTPUT"
+            extract() {
+              VALUE=$(echo "$RESPONSE" | grep -oP "$1" 2>/dev/null | head -n1)
+              VALUE=$(echo "$VALUE" | sed 's/^[ \t]*//;s/[ \t]*$//')
+              echo "${VALUE:-}"
+            }
 
-done
+            TIPO=$(extract '(?<=dxgv dx-al\" style=\"border-left-width:0px;border-right-width:0px;\">).*?(?=</td>)')
+            ESTADO=$(extract '(?<=color:#CC0000;font-weight:bold;border-left-width:0px;border-right-width:0px;\">).*?(?=</td>)')
+            APELLIDO=$(extract '(?<=txtApellidos\" value=\").*?(?=\")')
+            NOMBRE=$(extract '(?<=txtNombres\" value=\").*?(?=\")')
+            CODIGO=$(extract '(?<=txtCodigoCredencial&#39;\)\" value=\").*?(?=\")')
+            DNI=$(extract '(?<=txtRefExterna\" value=\").*?(?=\")')
+            ESTADO_CIVIL=$(extract '(?<=cboEstadoCivil_I\" type=\"text\" value=\").*?(?=\")')
+            EDAD=$(extract '(?<=txtEdad\" value=\").*?(?=\")')
+            FECHA_NAC=$(extract '(?<=txtFecNacimiento_I\" type=\"text\" value=\").*?(?=\")')
+            DISCAPACIDAD=$(extract '(?<=cboDiscapacitado_I\" type=\"text\" value=\").*?(?=\")')
+            FUERZA=$(extract '(?<=afiFA\">).*?(?=</span>)')
+            VIGENCIA=$(extract '(?<=txtFecha_Vigencia_I\" type=\"text\" value=\").*?(?=\")')
+            ALTA_ADMIN=$(extract '(?<=txtFecha_Alta_Administrativa_AcAs.*?value=\").*?(?=\")')
+            PROVINCIA=$(extract '(?<=cboProvincia_I\" type=\"text\" value=\").*?(?=\")')
+            LOCALIDAD=$(extract '(?<=cboLocalidad_I\" type=\"text\" value=\").*?(?=\")')
+            CALLE=$(extract '(?<=txtCalle\" value=\").*?(?=\")')
+            NUMERO=$(extract '(?<=txtNumero&#39;\).*?value=\").*?(?=\")')
 
-echo "Proceso finalizado. Archivo generado: $OUTPUT"
+            LINE="TIPO = $TIPO | ESTADO = $ESTADO | APELLIDO = $APELLIDO | NOMBRE = $NOMBRE | CODIGO = $CODIGO | DNI = $DNI | ESTADO CIVIL = $ESTADO_CIVIL | EDAD = $EDAD | FECHA DE NACIMIENTO = $FECHA_NAC | DISCAPACIDAD = $DISCAPACIDAD | FUERZAS DE ORIGEN = $FUERZA | VIGENCIA = $VIGENCIA | ALTA ADMINISTRATIVA = $ALTA_ADMIN | PROVIDENCIA = $PROVINCIA | LOCALIDAD = $LOCALIDAD | CALLE = $CALLE | NUMERO = $NUMERO"
+
+            echo "$LINE" >> "$OUTPUT"
+
+          done
+
+      - name: Crear Release
+        uses: softprops/action-gh-release@v2
+        with:
+          tag_name: resultado-${{ github.run_id }}
+          name: Resultado ${{ github.run_id }}
+          files: resultado.txt
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
